"""Initial migration

Revision ID: cba8a9105a12
Revises: 
Create Date: 2026-02-26 16:33:52.956394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba8a9105a12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inverters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('warranty', sa.Integer(), nullable=True),
    sa.Column('nominal_ac_power_kw', sa.Float(), nullable=False),
    sa.Column('max_dc_input_power', sa.Float(), nullable=True),
    sa.Column('mppt_min_voltage', sa.Float(), nullable=True),
    sa.Column('mppt_max_voltage', sa.Float(), nullable=True),
    sa.Column('max_dc_voltage', sa.Float(), nullable=True),
    sa.Column('max_dc_current_mppt', sa.Float(), nullable=True),
    sa.Column('no_of_mppt_ports', sa.Integer(), nullable=True),
    sa.Column('max_strings_per_mppt', sa.Integer(), nullable=True),
    sa.Column('efficiency_max', sa.Float(), nullable=True),
    sa.Column('ac_output_voltage', sa.String(length=50), nullable=True),
    sa.Column('phase_type', sa.String(length=20), nullable=True),
    sa.Column('spd_included', sa.Boolean(), nullable=True),
    sa.Column('ip_rating', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inverters_id'), 'inverters', ['id'], unique=False)
    op.create_index(op.f('ix_inverters_name'), 'inverters', ['name'], unique=False)
    op.create_table('panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('height_mm', sa.Float(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('warranty_years', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('panel_rated_power', sa.Float(), nullable=False),
    sa.Column('maximum_operating_voltage_vmpp', sa.Float(), nullable=True),
    sa.Column('maximum_operating_current_impp', sa.Float(), nullable=True),
    sa.Column('open_circuit_voltage', sa.Float(), nullable=True),
    sa.Column('short_circuit_current', sa.Float(), nullable=True),
    sa.Column('module_efficiency', sa.Float(), nullable=True),
    sa.Column('maximum_system_voltage', sa.Float(), nullable=True),
    sa.Column('maximum_series_fuse_rating', sa.Float(), nullable=True),
    sa.Column('num_of_cells', sa.Integer(), nullable=True),
    sa.Column('wind_load_kg_per_m2', sa.Float(), nullable=True),
    sa.Column('snow_load_kg_per_m2', sa.Float(), nullable=True),
    sa.Column('operating_temperature_from', sa.Float(), nullable=True),
    sa.Column('operating_temperature_to', sa.Float(), nullable=True),
    sa.Column('temp_coefficient_of_pmax', sa.Float(), nullable=True),
    sa.Column('temp_coefficient_of_voc', sa.Float(), nullable=True),
    sa.Column('temp_coefficient_of_isc', sa.Float(), nullable=True),
    sa.Column('nom_operating_cell_temp_noct', sa.Float(), nullable=True),
    sa.Column('connector_type', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panels_id'), 'panels', ['id'], unique=False)
    op.create_index(op.f('ix_panels_name'), 'panels', ['name'], unique=False)
    op.create_table('solar_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_solar_configs_key', 'solar_configs', ['key'], unique=False)
    op.create_index(op.f('ix_solar_configs_id'), 'solar_configs', ['id'], unique=False)
    op.create_index(op.f('ix_solar_configs_key'), 'solar_configs', ['key'], unique=True)
    op.create_table('utilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilities_id'), 'utilities', ['id'], unique=False)
    op.create_index(op.f('ix_utilities_name'), 'utilities', ['name'], unique=False)
    op.create_table('estimations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=True),
    sa.Column('utility_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('roof_image_path', sa.String(length=500), nullable=True),
    sa.Column('roof_polygon', sa.JSON(), nullable=True),
    sa.Column('roof_area', sa.Float(), nullable=True),
    sa.Column('building_floors', sa.Integer(), nullable=True),
    sa.Column('scale_meters_per_pixel', sa.Float(), nullable=True),
    sa.Column('usable_polygon', sa.JSON(), nullable=True),
    sa.Column('usable_area', sa.Float(), nullable=True),
    sa.Column('usable_area_m2', sa.Float(), nullable=True),
    sa.Column('roof_mask_image', sa.Text(), nullable=True),
    sa.Column('overlay_image', sa.Text(), nullable=True),
    sa.Column('sam_masks', sa.JSON(), nullable=True),
    sa.Column('roof_mask_index', sa.Integer(), nullable=True),
    sa.Column('facade_reduction_ratio', sa.Float(), nullable=True),
    sa.Column('roof_type_detected', sa.String(length=100), nullable=True),
    sa.Column('facade_filtering_applied', sa.Boolean(), nullable=True),
    sa.Column('meters_per_pixel', sa.Float(), nullable=True),
    sa.Column('panel_grid_image', sa.Text(), nullable=True),
    sa.Column('visualization_image', sa.Text(), nullable=True),
    sa.Column('panel_grid', sa.JSON(), nullable=True),
    sa.Column('panel_positions', sa.JSON(), nullable=True),
    sa.Column('annual_usage_kwh', sa.Float(), nullable=True),
    sa.Column('annual_cost', sa.Float(), nullable=True),
    sa.Column('monthly_usage', sa.JSON(), nullable=True),
    sa.Column('monthly_cost', sa.JSON(), nullable=True),
    sa.Column('utility_company', sa.String(length=255), nullable=True),
    sa.Column('coverage_percentage', sa.Integer(), nullable=True),
    sa.Column('energy_usage_type', sa.String(length=50), nullable=True),
    sa.Column('panel_count', sa.Integer(), nullable=True),
    sa.Column('system_capacity', sa.Float(), nullable=False),
    sa.Column('tilt', sa.Float(), nullable=False),
    sa.Column('azimuth', sa.Float(), nullable=False),
    sa.Column('losses', sa.Float(), nullable=True),
    sa.Column('dc_monthly', sa.JSON(), nullable=True),
    sa.Column('poa_monthly', sa.JSON(), nullable=True),
    sa.Column('solrad_monthly', sa.JSON(), nullable=True),
    sa.Column('ac_monthly', sa.JSON(), nullable=True),
    sa.Column('energy_annual', sa.Float(), nullable=False),
    sa.Column('capacity_factor', sa.Float(), nullable=True),
    sa.Column('solrad_annual', sa.Float(), nullable=True),
    sa.Column('optimum_tilt', sa.Float(), nullable=True),
    sa.Column('optimum_azimuth', sa.Float(), nullable=True),
    sa.Column('total_losses_percent', sa.Float(), nullable=True),
    sa.Column('roof_type', sa.String(length=100), nullable=True),
    sa.Column('roof_tilt', sa.Float(), nullable=True),
    sa.Column('roof_net_tilt', sa.Float(), nullable=True),
    sa.Column('annual_production_per_kw', sa.Float(), nullable=True),
    sa.Column('solar_irradiance_avg', sa.Float(), nullable=True),
    sa.Column('performance_ratio', sa.Float(), nullable=True),
    sa.Column('solar_production_factor', sa.Float(), nullable=True),
    sa.Column('mounting_structure_cost', sa.Float(), nullable=True),
    sa.Column('installation_type', sa.String(length=100), nullable=True),
    sa.Column('panel_orientation', sa.String(length=100), nullable=True),
    sa.Column('inverter_design', sa.JSON(), nullable=True),
    sa.Column('inverter_combos', sa.JSON(), nullable=True),
    sa.Column('stringing_details', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'COMPLETED', 'FAILED', name='estimationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimations_id'), 'estimations', ['id'], unique=False)
    op.create_table('utility_rate_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('range_name', sa.String(length=100), nullable=True),
    sa.Column('min_usage', sa.Float(), nullable=False),
    sa.Column('max_usage', sa.Float(), nullable=True),
    sa.Column('rate_per_kwh', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utility_rate_ranges_id'), 'utility_rate_ranges', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utility_rate_ranges_id'), table_name='utility_rate_ranges')
    op.drop_table('utility_rate_ranges')
    op.drop_index(op.f('ix_estimations_id'), table_name='estimations')
    op.drop_table('estimations')
    op.drop_index(op.f('ix_utilities_name'), table_name='utilities')
    op.drop_index(op.f('ix_utilities_id'), table_name='utilities')
    op.drop_table('utilities')
    op.drop_index(op.f('ix_solar_configs_key'), table_name='solar_configs')
    op.drop_index(op.f('ix_solar_configs_id'), table_name='solar_configs')
    op.drop_index('idx_solar_configs_key', table_name='solar_configs')
    op.drop_table('solar_configs')
    op.drop_index(op.f('ix_panels_name'), table_name='panels')
    op.drop_index(op.f('ix_panels_id'), table_name='panels')
    op.drop_table('panels')
    op.drop_index(op.f('ix_inverters_name'), table_name='inverters')
    op.drop_index(op.f('ix_inverters_id'), table_name='inverters')
    op.drop_table('inverters')
    # ### end Alembic commands ###
