"""add_loss_breakdown_column

Revision ID: 173427db018c
Revises: cba8a9105a12
Create Date: 2026-02-28 14:56:36.467519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '173427db018c'
down_revision: Union[str, None] = 'cba8a9105a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimations', sa.Column('loss_breakdown', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimations', 'loss_breakdown')
    # ### end Alembic commands ###
