"""add_user_id_to_estimations

Revision ID: 0fd635509d4e
Revises: b2c3d4e5f601
Create Date: 2026-03-01 12:08:01.859614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd635509d4e'
down_revision: Union[str, None] = 'b2c3d4e5f601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_estimations_user_id'), 'estimations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'estimations', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'estimations', type_='foreignkey')
    op.drop_index(op.f('ix_estimations_user_id'), table_name='estimations')
    op.drop_column('estimations', 'user_id')
    # ### end Alembic commands ###
